CONTROLLER_PORT = 0


class CanBusIds:
    LEFT_LEADER_MOTOR = 1
    LEFT_FOLLOWER_MOTOR = 2
    RIGHT_LEADER_MOTOR = 3
    RIGHT_FOLLOWER_MOTOR = 4
    ROLLER_MOTOR = 5


class Robot:
    NAME = "KitBot"
