DRIVETRAIN_TYPE = "tank"

# CAN bus ids
CAN_LEFT_DRIVE_MOTOR_1 = 1
CAN_LEFT_DRIVE_MOTOR_2 = 2
CAN_RIGHT_DRIVE_MOTOR_1 = 3
CAN_RIGHT_DRIVE_MOTOR_2 = 4

# Controller Settings
CONTROLLER_TYPE = "Xbox"
CONTROLLER_PORT = 0
JOYSTICK_LEFT_X = 0
JOYSTICK_LEFT_Y = 1
JOYSTICK_RIGHT_X = 4
JOYSTICK_RIGHT_Y = 5
